version: 2.1 #teb3a circleci
orbs:
  heroku: circleci/heroku@0.0.10 #ma3neha ynajem ya7ki m3a heroku
workflows:  #chenbeldi el appeli metkawna men jobs w feha steps
  build_deploy:
    jobs:
      - build
      - deploy_production: #bch ndeployiw elpp
        requires: #maye5dem ken k ye5dem el build 
          - build

jobs:
  build:
    docker:
      - image: circleci/node #3andhoum lesimages mte3houm bch ysobortiw el app
    working_directory: ~/repo
    steps:
      - checkout #rani chenjib elcode
      - run: yarn install #kima npm install bch njib les dependances(ya9ra el fichier config.json w yanstalli les dependances elkol)
      - run: yarn test #chenraniw les test fel circle ci 
  deploy_production:
    environment: #variable denvvironnement
      HEROKU_APP_NAME: worshopossec
    executor: heroku/default #stage hetha chyest7e9 el extention 
    steps:

      - checkout
      - heroku/install #heroku install
      - heroku/deploy-via-git: #deploy eli jebou mel git 

          only-branch: master